### ISSUE TITLE
Job fails

### ISSUE THREAD

**Issue by x3rt** [ricado-group/dotnet-library-build-release-action#5]
The job fails whenever it is ran. [Logs attached](https://github.com/ricado-group/dotnet-library-build-release-action/files/8456787/logs.txt)

my workflow is set up as the following
```yml
name: Publish Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: .NET Library Build and Release
        uses: ricado-group/dotnet-library-build-release-action@v1
        with:
          project-name: 'x3rt.KurvaBot'   
          github-token: ${{ secrets.GITHUB_TOKEN }}
          private-nuget-url: 'https://nuget.pkg.github.com/x3rt/index.json'
          private-nuget-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          public-nuget-token: ${{ secrets.NUGET_APIKEY }}
```
